package:
  name: esr_task
  version: 0.1

source:
  path: .

build:
  script:
    - $PYTHON setup.py install
  entry_points:
    - covid_comp = cli.cli_covid_comparison:main
    - car = cli.cli_car:main

requirements:
  build:
    - python
    - setuptools
  run:
    - tslearn
    - pandas
    - scikit-learn
    - matplotlib==3.6.0
    - pyyaml
    - pytorch 
    - u8darts-all
    - jpeg==9e
    - tensorboard